version: "3"
services:

  server-center:
    image: "bndynet/sc-server-center"
    restart: always
    ports:
     - "9000:9000"
     
  server-config:
    image: "bndynet/sc-server-config"
    restart: always
    ports:
      - "9010:9010"
    depends_on:
      - server-center

  server-gateway:
    image: "bndynet/sc-server-gateway"
    restart: always
    ports:
      - "9020:9020"
    depends_on:
      - server-center
      
  service-oauth:
    image: "bndynet/sc-service-oauth"
    restart: on-failure:3
    ports:
      - "9100:9100"
    depends_on:
      - server-center
      - server-config
      - server-gateway

  service-sso:
    image: "bndynet/sc-service-sso"
    restart: on-failure:3
    ports:
      - "9110:9110"
    depends_on:
      - server-center
      - server-config
      - server-gateway