server:
  port: 8081
#  servlet:
#    context-path: /resource-server

logging:
  level:
    root: DEBUG

spring:
  application:
    name: Resource Service
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myDb
    username: root
    password: 123456

  security:
    oauth2:
      resourceserver:
        jwt:
#          issuer-uri: http://127.0.0.1:8080/auth/realms/master
          jwk-set-uri: http://127.0.0.1:9900/auth/realms/master/protocol/openid-connect/certs

knife4j:
  enable: true
  production: false
  setting:
    language: en-US
    enableAfterScript: false
#    enableHomeCustom: true
#    homeCustomLocation: classpath:README.md
    enableFooter: false
    enableFooterCustom: true
    footerCustomContent: Copyright (c) [Bndy.Net](http://bndy.net) 2021
    enableSwaggerModels: true
    swaggerModelName: Models
