package net.bndy.sc.service.sso.dao;

import java.util.List;
import net.bndy.sc.service.sso.model.OAuthClientDetail;
import net.bndy.sc.service.sso.model.OAuthClientDetailExample;
import org.apache.ibatis.annotations.Param;

public interface OAuthClientDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Tue Aug 07 09:26:54 CST 2018
     */
    long countByExample(OAuthClientDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Tue Aug 07 09:26:54 CST 2018
     */
    int deleteByExample(OAuthClientDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Tue Aug 07 09:26:54 CST 2018
     */
    int deleteByPrimaryKey(String client_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Tue Aug 07 09:26:54 CST 2018
     */
    int insert(OAuthClientDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Tue Aug 07 09:26:54 CST 2018
     */
    int insertSelective(OAuthClientDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Tue Aug 07 09:26:54 CST 2018
     */
    List<OAuthClientDetail> selectByExample(OAuthClientDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Tue Aug 07 09:26:54 CST 2018
     */
    OAuthClientDetail selectByPrimaryKey(String client_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Tue Aug 07 09:26:54 CST 2018
     */
    int updateByExampleSelective(@Param("record") OAuthClientDetail record, @Param("example") OAuthClientDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Tue Aug 07 09:26:54 CST 2018
     */
    int updateByExample(@Param("record") OAuthClientDetail record, @Param("example") OAuthClientDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Tue Aug 07 09:26:54 CST 2018
     */
    int updateByPrimaryKeySelective(OAuthClientDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Tue Aug 07 09:26:54 CST 2018
     */
    int updateByPrimaryKey(OAuthClientDetail record);
}