package net.bndy.sc.service.sso.dao;

import java.util.List;
import net.bndy.sc.service.sso.model.OauthCode;
import net.bndy.sc.service.sso.model.OauthCodeCriteria;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface OauthCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_code
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    @SelectProvider(type=OauthCodeSqlProvider.class, method="countByExample")
    long countByExample(OauthCodeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_code
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    @DeleteProvider(type=OauthCodeSqlProvider.class, method="deleteByExample")
    int deleteByExample(OauthCodeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_code
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    @Insert({
        "insert into oauth_code (code, authentication)",
        "values (#{code,jdbcType=VARCHAR}, #{authentication,jdbcType=LONGVARBINARY})"
    })
    int insert(OauthCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_code
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    @InsertProvider(type=OauthCodeSqlProvider.class, method="insertSelective")
    int insertSelective(OauthCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_code
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    @SelectProvider(type=OauthCodeSqlProvider.class, method="selectByExampleWithBLOBs")
    @Results({
        @Result(column="code", property="code", jdbcType=JdbcType.VARCHAR),
        @Result(column="authentication", property="authentication", jdbcType=JdbcType.LONGVARBINARY)
    })
    List<OauthCode> selectByExampleWithBLOBs(OauthCodeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_code
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    @SelectProvider(type=OauthCodeSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="code", property="code", jdbcType=JdbcType.VARCHAR)
    })
    List<OauthCode> selectByExample(OauthCodeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_code
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    @UpdateProvider(type=OauthCodeSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") OauthCode record, @Param("example") OauthCodeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_code
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    @UpdateProvider(type=OauthCodeSqlProvider.class, method="updateByExampleWithBLOBs")
    int updateByExampleWithBLOBs(@Param("record") OauthCode record, @Param("example") OauthCodeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_code
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    @UpdateProvider(type=OauthCodeSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") OauthCode record, @Param("example") OauthCodeCriteria example);
}