package net.bndy.sc.service.sso.dao;

import java.util.List;
import net.bndy.sc.service.sso.model.OauthClientDetails;
import net.bndy.sc.service.sso.model.OauthClientDetailsCriteria;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface OauthClientDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    @SelectProvider(type=OauthClientDetailsSqlProvider.class, method="countByExample")
    long countByExample(OauthClientDetailsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    @DeleteProvider(type=OauthClientDetailsSqlProvider.class, method="deleteByExample")
    int deleteByExample(OauthClientDetailsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    @Delete({
        "delete from oauth_client_details",
        "where client_id = #{client_id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String client_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    @Insert({
        "insert into oauth_client_details (client_id, client_name, ",
        "client_secret, resource_ids, ",
        "scope, authorized_grant_types, ",
        "web_server_redirect_uri, authorities, ",
        "access_token_validity, refresh_token_validity, ",
        "additional_information, autoapprove)",
        "values (#{client_id,jdbcType=VARCHAR}, #{client_name,jdbcType=VARCHAR}, ",
        "#{client_secret,jdbcType=VARCHAR}, #{resource_ids,jdbcType=VARCHAR}, ",
        "#{scope,jdbcType=VARCHAR}, #{authorized_grant_types,jdbcType=VARCHAR}, ",
        "#{web_server_redirect_uri,jdbcType=VARCHAR}, #{authorities,jdbcType=VARCHAR}, ",
        "#{access_token_validity,jdbcType=INTEGER}, #{refresh_token_validity,jdbcType=INTEGER}, ",
        "#{additional_information,jdbcType=VARCHAR}, #{autoapprove,jdbcType=TINYINT})"
    })
    int insert(OauthClientDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    @InsertProvider(type=OauthClientDetailsSqlProvider.class, method="insertSelective")
    int insertSelective(OauthClientDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    @SelectProvider(type=OauthClientDetailsSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="client_id", property="client_id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="client_name", property="client_name", jdbcType=JdbcType.VARCHAR),
        @Result(column="client_secret", property="client_secret", jdbcType=JdbcType.VARCHAR),
        @Result(column="resource_ids", property="resource_ids", jdbcType=JdbcType.VARCHAR),
        @Result(column="scope", property="scope", jdbcType=JdbcType.VARCHAR),
        @Result(column="authorized_grant_types", property="authorized_grant_types", jdbcType=JdbcType.VARCHAR),
        @Result(column="web_server_redirect_uri", property="web_server_redirect_uri", jdbcType=JdbcType.VARCHAR),
        @Result(column="authorities", property="authorities", jdbcType=JdbcType.VARCHAR),
        @Result(column="access_token_validity", property="access_token_validity", jdbcType=JdbcType.INTEGER),
        @Result(column="refresh_token_validity", property="refresh_token_validity", jdbcType=JdbcType.INTEGER),
        @Result(column="additional_information", property="additional_information", jdbcType=JdbcType.VARCHAR),
        @Result(column="autoapprove", property="autoapprove", jdbcType=JdbcType.TINYINT)
    })
    List<OauthClientDetails> selectByExample(OauthClientDetailsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    @Select({
        "select",
        "client_id, client_name, client_secret, resource_ids, scope, authorized_grant_types, ",
        "web_server_redirect_uri, authorities, access_token_validity, refresh_token_validity, ",
        "additional_information, autoapprove",
        "from oauth_client_details",
        "where client_id = #{client_id,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="client_id", property="client_id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="client_name", property="client_name", jdbcType=JdbcType.VARCHAR),
        @Result(column="client_secret", property="client_secret", jdbcType=JdbcType.VARCHAR),
        @Result(column="resource_ids", property="resource_ids", jdbcType=JdbcType.VARCHAR),
        @Result(column="scope", property="scope", jdbcType=JdbcType.VARCHAR),
        @Result(column="authorized_grant_types", property="authorized_grant_types", jdbcType=JdbcType.VARCHAR),
        @Result(column="web_server_redirect_uri", property="web_server_redirect_uri", jdbcType=JdbcType.VARCHAR),
        @Result(column="authorities", property="authorities", jdbcType=JdbcType.VARCHAR),
        @Result(column="access_token_validity", property="access_token_validity", jdbcType=JdbcType.INTEGER),
        @Result(column="refresh_token_validity", property="refresh_token_validity", jdbcType=JdbcType.INTEGER),
        @Result(column="additional_information", property="additional_information", jdbcType=JdbcType.VARCHAR),
        @Result(column="autoapprove", property="autoapprove", jdbcType=JdbcType.TINYINT)
    })
    OauthClientDetails selectByPrimaryKey(String client_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    @UpdateProvider(type=OauthClientDetailsSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") OauthClientDetails record, @Param("example") OauthClientDetailsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    @UpdateProvider(type=OauthClientDetailsSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") OauthClientDetails record, @Param("example") OauthClientDetailsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    @UpdateProvider(type=OauthClientDetailsSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(OauthClientDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    @Update({
        "update oauth_client_details",
        "set client_name = #{client_name,jdbcType=VARCHAR},",
          "client_secret = #{client_secret,jdbcType=VARCHAR},",
          "resource_ids = #{resource_ids,jdbcType=VARCHAR},",
          "scope = #{scope,jdbcType=VARCHAR},",
          "authorized_grant_types = #{authorized_grant_types,jdbcType=VARCHAR},",
          "web_server_redirect_uri = #{web_server_redirect_uri,jdbcType=VARCHAR},",
          "authorities = #{authorities,jdbcType=VARCHAR},",
          "access_token_validity = #{access_token_validity,jdbcType=INTEGER},",
          "refresh_token_validity = #{refresh_token_validity,jdbcType=INTEGER},",
          "additional_information = #{additional_information,jdbcType=VARCHAR},",
          "autoapprove = #{autoapprove,jdbcType=TINYINT}",
        "where client_id = #{client_id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(OauthClientDetails record);
}