package net.bndy.sc.service.sso.dao;

import java.util.List;
import net.bndy.sc.service.sso.model.OauthAccessToken;
import net.bndy.sc.service.sso.model.OauthAccessTokenCriteria;
import net.bndy.sc.service.sso.model.OauthAccessTokenWithBLOBs;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface OauthAccessTokenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_access_token
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    @SelectProvider(type=OauthAccessTokenSqlProvider.class, method="countByExample")
    long countByExample(OauthAccessTokenCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_access_token
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    @DeleteProvider(type=OauthAccessTokenSqlProvider.class, method="deleteByExample")
    int deleteByExample(OauthAccessTokenCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_access_token
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    @Insert({
        "insert into oauth_access_token (token_id, authentication_id, ",
        "user_name, client_id, ",
        "refresh_token, token, ",
        "authentication)",
        "values (#{token_id,jdbcType=VARCHAR}, #{authentication_id,jdbcType=VARCHAR}, ",
        "#{user_name,jdbcType=VARCHAR}, #{client_id,jdbcType=VARCHAR}, ",
        "#{refresh_token,jdbcType=VARCHAR}, #{token,jdbcType=LONGVARBINARY}, ",
        "#{authentication,jdbcType=LONGVARBINARY})"
    })
    int insert(OauthAccessTokenWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_access_token
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    @InsertProvider(type=OauthAccessTokenSqlProvider.class, method="insertSelective")
    int insertSelective(OauthAccessTokenWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_access_token
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    @SelectProvider(type=OauthAccessTokenSqlProvider.class, method="selectByExampleWithBLOBs")
    @Results({
        @Result(column="token_id", property="token_id", jdbcType=JdbcType.VARCHAR),
        @Result(column="authentication_id", property="authentication_id", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_name", property="user_name", jdbcType=JdbcType.VARCHAR),
        @Result(column="client_id", property="client_id", jdbcType=JdbcType.VARCHAR),
        @Result(column="refresh_token", property="refresh_token", jdbcType=JdbcType.VARCHAR),
        @Result(column="token", property="token", jdbcType=JdbcType.LONGVARBINARY),
        @Result(column="authentication", property="authentication", jdbcType=JdbcType.LONGVARBINARY)
    })
    List<OauthAccessTokenWithBLOBs> selectByExampleWithBLOBs(OauthAccessTokenCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_access_token
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    @SelectProvider(type=OauthAccessTokenSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="token_id", property="token_id", jdbcType=JdbcType.VARCHAR),
        @Result(column="authentication_id", property="authentication_id", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_name", property="user_name", jdbcType=JdbcType.VARCHAR),
        @Result(column="client_id", property="client_id", jdbcType=JdbcType.VARCHAR),
        @Result(column="refresh_token", property="refresh_token", jdbcType=JdbcType.VARCHAR)
    })
    List<OauthAccessToken> selectByExample(OauthAccessTokenCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_access_token
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    @UpdateProvider(type=OauthAccessTokenSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") OauthAccessTokenWithBLOBs record, @Param("example") OauthAccessTokenCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_access_token
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    @UpdateProvider(type=OauthAccessTokenSqlProvider.class, method="updateByExampleWithBLOBs")
    int updateByExampleWithBLOBs(@Param("record") OauthAccessTokenWithBLOBs record, @Param("example") OauthAccessTokenCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_access_token
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    @UpdateProvider(type=OauthAccessTokenSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") OauthAccessToken record, @Param("example") OauthAccessTokenCriteria example);
}