package net.bndy.sc.service.sso.dao;

import java.util.List;
import net.bndy.sc.service.sso.model.OauthApprovals;
import net.bndy.sc.service.sso.model.OauthApprovalsCriteria;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface OauthApprovalsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_approvals
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    @SelectProvider(type=OauthApprovalsSqlProvider.class, method="countByExample")
    long countByExample(OauthApprovalsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_approvals
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    @DeleteProvider(type=OauthApprovalsSqlProvider.class, method="deleteByExample")
    int deleteByExample(OauthApprovalsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_approvals
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    @Insert({
        "insert into oauth_approvals (userId, clientId, ",
        "scope, status, expiresAt, ",
        "lastModifiedAt)",
        "values (#{userId,jdbcType=VARCHAR}, #{clientId,jdbcType=VARCHAR}, ",
        "#{scope,jdbcType=VARCHAR}, #{status,jdbcType=VARCHAR}, #{expiresAt,jdbcType=TIMESTAMP}, ",
        "#{lastModifiedAt,jdbcType=TIMESTAMP})"
    })
    int insert(OauthApprovals record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_approvals
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    @InsertProvider(type=OauthApprovalsSqlProvider.class, method="insertSelective")
    int insertSelective(OauthApprovals record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_approvals
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    @SelectProvider(type=OauthApprovalsSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="userId", property="userId", jdbcType=JdbcType.VARCHAR),
        @Result(column="clientId", property="clientId", jdbcType=JdbcType.VARCHAR),
        @Result(column="scope", property="scope", jdbcType=JdbcType.VARCHAR),
        @Result(column="status", property="status", jdbcType=JdbcType.VARCHAR),
        @Result(column="expiresAt", property="expiresAt", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="lastModifiedAt", property="lastModifiedAt", jdbcType=JdbcType.TIMESTAMP)
    })
    List<OauthApprovals> selectByExample(OauthApprovalsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_approvals
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    @UpdateProvider(type=OauthApprovalsSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") OauthApprovals record, @Param("example") OauthApprovalsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_approvals
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    @UpdateProvider(type=OauthApprovalsSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") OauthApprovals record, @Param("example") OauthApprovalsCriteria example);
}