package net.bndy.sc.service.sso.dao;

import java.util.List;
import java.util.Map;
import net.bndy.sc.service.sso.model.OauthAccessTokenCriteria.Criteria;
import net.bndy.sc.service.sso.model.OauthAccessTokenCriteria.Criterion;
import net.bndy.sc.service.sso.model.OauthAccessTokenCriteria;
import net.bndy.sc.service.sso.model.OauthAccessTokenWithBLOBs;
import org.apache.ibatis.jdbc.SQL;

public class OauthAccessTokenSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_access_token
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    public String countByExample(OauthAccessTokenCriteria example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("oauth_access_token");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_access_token
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    public String deleteByExample(OauthAccessTokenCriteria example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("oauth_access_token");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_access_token
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    public String insertSelective(OauthAccessTokenWithBLOBs record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("oauth_access_token");
        
        if (record.getToken_id() != null) {
            sql.VALUES("token_id", "#{token_id,jdbcType=VARCHAR}");
        }
        
        if (record.getAuthentication_id() != null) {
            sql.VALUES("authentication_id", "#{authentication_id,jdbcType=VARCHAR}");
        }
        
        if (record.getUser_name() != null) {
            sql.VALUES("user_name", "#{user_name,jdbcType=VARCHAR}");
        }
        
        if (record.getClient_id() != null) {
            sql.VALUES("client_id", "#{client_id,jdbcType=VARCHAR}");
        }
        
        if (record.getRefresh_token() != null) {
            sql.VALUES("refresh_token", "#{refresh_token,jdbcType=VARCHAR}");
        }
        
        if (record.getToken() != null) {
            sql.VALUES("token", "#{token,jdbcType=LONGVARBINARY}");
        }
        
        if (record.getAuthentication() != null) {
            sql.VALUES("authentication", "#{authentication,jdbcType=LONGVARBINARY}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_access_token
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    public String selectByExampleWithBLOBs(OauthAccessTokenCriteria example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("token_id");
        } else {
            sql.SELECT("token_id");
        }
        sql.SELECT("authentication_id");
        sql.SELECT("user_name");
        sql.SELECT("client_id");
        sql.SELECT("refresh_token");
        sql.SELECT("token");
        sql.SELECT("authentication");
        sql.FROM("oauth_access_token");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_access_token
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    public String selectByExample(OauthAccessTokenCriteria example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("token_id");
        } else {
            sql.SELECT("token_id");
        }
        sql.SELECT("authentication_id");
        sql.SELECT("user_name");
        sql.SELECT("client_id");
        sql.SELECT("refresh_token");
        sql.FROM("oauth_access_token");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_access_token
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        OauthAccessTokenWithBLOBs record = (OauthAccessTokenWithBLOBs) parameter.get("record");
        OauthAccessTokenCriteria example = (OauthAccessTokenCriteria) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("oauth_access_token");
        
        if (record.getToken_id() != null) {
            sql.SET("token_id = #{record.token_id,jdbcType=VARCHAR}");
        }
        
        if (record.getAuthentication_id() != null) {
            sql.SET("authentication_id = #{record.authentication_id,jdbcType=VARCHAR}");
        }
        
        if (record.getUser_name() != null) {
            sql.SET("user_name = #{record.user_name,jdbcType=VARCHAR}");
        }
        
        if (record.getClient_id() != null) {
            sql.SET("client_id = #{record.client_id,jdbcType=VARCHAR}");
        }
        
        if (record.getRefresh_token() != null) {
            sql.SET("refresh_token = #{record.refresh_token,jdbcType=VARCHAR}");
        }
        
        if (record.getToken() != null) {
            sql.SET("token = #{record.token,jdbcType=LONGVARBINARY}");
        }
        
        if (record.getAuthentication() != null) {
            sql.SET("authentication = #{record.authentication,jdbcType=LONGVARBINARY}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_access_token
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    public String updateByExampleWithBLOBs(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("oauth_access_token");
        
        sql.SET("token_id = #{record.token_id,jdbcType=VARCHAR}");
        sql.SET("authentication_id = #{record.authentication_id,jdbcType=VARCHAR}");
        sql.SET("user_name = #{record.user_name,jdbcType=VARCHAR}");
        sql.SET("client_id = #{record.client_id,jdbcType=VARCHAR}");
        sql.SET("refresh_token = #{record.refresh_token,jdbcType=VARCHAR}");
        sql.SET("token = #{record.token,jdbcType=LONGVARBINARY}");
        sql.SET("authentication = #{record.authentication,jdbcType=LONGVARBINARY}");
        
        OauthAccessTokenCriteria example = (OauthAccessTokenCriteria) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_access_token
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("oauth_access_token");
        
        sql.SET("token_id = #{record.token_id,jdbcType=VARCHAR}");
        sql.SET("authentication_id = #{record.authentication_id,jdbcType=VARCHAR}");
        sql.SET("user_name = #{record.user_name,jdbcType=VARCHAR}");
        sql.SET("client_id = #{record.client_id,jdbcType=VARCHAR}");
        sql.SET("refresh_token = #{record.refresh_token,jdbcType=VARCHAR}");
        
        OauthAccessTokenCriteria example = (OauthAccessTokenCriteria) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_access_token
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    protected void applyWhere(SQL sql, OauthAccessTokenCriteria example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}