package net.bndy.sc.service.sso.dao;

import java.util.List;
import net.bndy.sc.service.sso.model.OauthClientToken;
import net.bndy.sc.service.sso.model.OauthClientTokenCriteria;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface OauthClientTokenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_token
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    @SelectProvider(type=OauthClientTokenSqlProvider.class, method="countByExample")
    long countByExample(OauthClientTokenCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_token
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    @DeleteProvider(type=OauthClientTokenSqlProvider.class, method="deleteByExample")
    int deleteByExample(OauthClientTokenCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_token
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    @Insert({
        "insert into oauth_client_token (token_id, authentication_id, ",
        "user_name, client_id, ",
        "token)",
        "values (#{token_id,jdbcType=VARCHAR}, #{authentication_id,jdbcType=VARCHAR}, ",
        "#{user_name,jdbcType=VARCHAR}, #{client_id,jdbcType=VARCHAR}, ",
        "#{token,jdbcType=LONGVARBINARY})"
    })
    int insert(OauthClientToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_token
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    @InsertProvider(type=OauthClientTokenSqlProvider.class, method="insertSelective")
    int insertSelective(OauthClientToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_token
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    @SelectProvider(type=OauthClientTokenSqlProvider.class, method="selectByExampleWithBLOBs")
    @Results({
        @Result(column="token_id", property="token_id", jdbcType=JdbcType.VARCHAR),
        @Result(column="authentication_id", property="authentication_id", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_name", property="user_name", jdbcType=JdbcType.VARCHAR),
        @Result(column="client_id", property="client_id", jdbcType=JdbcType.VARCHAR),
        @Result(column="token", property="token", jdbcType=JdbcType.LONGVARBINARY)
    })
    List<OauthClientToken> selectByExampleWithBLOBs(OauthClientTokenCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_token
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    @SelectProvider(type=OauthClientTokenSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="token_id", property="token_id", jdbcType=JdbcType.VARCHAR),
        @Result(column="authentication_id", property="authentication_id", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_name", property="user_name", jdbcType=JdbcType.VARCHAR),
        @Result(column="client_id", property="client_id", jdbcType=JdbcType.VARCHAR)
    })
    List<OauthClientToken> selectByExample(OauthClientTokenCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_token
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    @UpdateProvider(type=OauthClientTokenSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") OauthClientToken record, @Param("example") OauthClientTokenCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_token
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    @UpdateProvider(type=OauthClientTokenSqlProvider.class, method="updateByExampleWithBLOBs")
    int updateByExampleWithBLOBs(@Param("record") OauthClientToken record, @Param("example") OauthClientTokenCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_token
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    @UpdateProvider(type=OauthClientTokenSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") OauthClientToken record, @Param("example") OauthClientTokenCriteria example);
}