version: "3"
services:

  server:
    image: "bndynet/sc-server"
    ports:
     - "9000:9000"

  gateway:
    image: "bndynet/sc-gateway"
    ports:
      - "8081:9010"
    depends_on:
      - server
      
  service-oauth:
    image: "bndynet/sc-service-oauth"
    ports:
      - "8088:9100"
    depends_on:
      - server
      - gateway