server:
  port: 9110
  error:
    whitelabel:
      enabled: false
    # include-stacktrace: always
    
spring:
  application:
    name: service-sso

  banner:
    location: classpath:banner.txt

  messages:
    basename: i18n/messages
    
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: false
    hibernate:
      ddl-auto: update
    
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sso
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
