server:
  port: 9110
  error:
    whitelabel:
      enabled: false
    # include-stacktrace: always
    
spring:
  application:
    name: service-sso

  banner:
    location: classpath:banner.txt

  messages:
    basename: i18n/messages
    
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: false
        jdbc:
          time_zone = UTC
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sso
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:123456}
    driver-class-name: com.mysql.jdbc.Driver
    
  session:
    store-type: redis
    redis:
      flush-mode: on-save
      namespace: spring:session

  redis:
    host: localhost
    password:
    port: 6379
    timeout: 10000
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
