server:
  port: 9020

spring:
  application:
    name: server-gateway
  banner:
    location: classpath:banner.txt

eureka:
  client:
    serviceUrl:
      defaultZone: http://server-center:9000/eureka
      
zuul:
  routes:
    oauth:
      path: /oauth/**
      service-id: service-oauth

    sso:
      path: /sso/**
      service-id: service-sso