package net.bndy.sc.service.sso.model;

import java.io.Serializable;
import java.util.Arrays;

public class OauthRefreshToken implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_refresh_token.token_id
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    private String token_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_refresh_token.token
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    private byte[] token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_refresh_token.authentication
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    private byte[] authentication;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oauth_refresh_token
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_refresh_token.token_id
     *
     * @return the value of oauth_refresh_token.token_id
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    public String getToken_id() {
        return token_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_refresh_token.token_id
     *
     * @param token_id the value for oauth_refresh_token.token_id
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    public void setToken_id(String token_id) {
        this.token_id = token_id == null ? null : token_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_refresh_token.token
     *
     * @return the value of oauth_refresh_token.token
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    public byte[] getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_refresh_token.token
     *
     * @param token the value for oauth_refresh_token.token
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    public void setToken(byte[] token) {
        this.token = token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_refresh_token.authentication
     *
     * @return the value of oauth_refresh_token.authentication
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    public byte[] getAuthentication() {
        return authentication;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_refresh_token.authentication
     *
     * @param authentication the value for oauth_refresh_token.authentication
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    public void setAuthentication(byte[] authentication) {
        this.authentication = authentication;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_refresh_token
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        OauthRefreshToken other = (OauthRefreshToken) that;
        return (this.getToken_id() == null ? other.getToken_id() == null : this.getToken_id().equals(other.getToken_id()))
            && (Arrays.equals(this.getToken(), other.getToken()))
            && (Arrays.equals(this.getAuthentication(), other.getAuthentication()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_refresh_token
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getToken_id() == null) ? 0 : getToken_id().hashCode());
        result = prime * result + (Arrays.hashCode(getToken()));
        result = prime * result + (Arrays.hashCode(getAuthentication()));
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_refresh_token
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", token_id=").append(token_id);
        sb.append(", token=").append(token);
        sb.append(", authentication=").append(authentication);
        sb.append("]");
        return sb.toString();
    }
}