package net.bndy.sc.service.sso.model;

import java.io.Serializable;
import java.util.Arrays;

public class OauthAccessTokenWithBLOBs extends OauthAccessToken implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_access_token.token
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    private byte[] token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_access_token.authentication
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    private byte[] authentication;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oauth_access_token
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_access_token.token
     *
     * @return the value of oauth_access_token.token
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    public byte[] getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_access_token.token
     *
     * @param token the value for oauth_access_token.token
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    public void setToken(byte[] token) {
        this.token = token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_access_token.authentication
     *
     * @return the value of oauth_access_token.authentication
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    public byte[] getAuthentication() {
        return authentication;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_access_token.authentication
     *
     * @param authentication the value for oauth_access_token.authentication
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    public void setAuthentication(byte[] authentication) {
        this.authentication = authentication;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_access_token
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        OauthAccessTokenWithBLOBs other = (OauthAccessTokenWithBLOBs) that;
        return (this.getToken_id() == null ? other.getToken_id() == null : this.getToken_id().equals(other.getToken_id()))
            && (this.getAuthentication_id() == null ? other.getAuthentication_id() == null : this.getAuthentication_id().equals(other.getAuthentication_id()))
            && (this.getUser_name() == null ? other.getUser_name() == null : this.getUser_name().equals(other.getUser_name()))
            && (this.getClient_id() == null ? other.getClient_id() == null : this.getClient_id().equals(other.getClient_id()))
            && (this.getRefresh_token() == null ? other.getRefresh_token() == null : this.getRefresh_token().equals(other.getRefresh_token()))
            && (Arrays.equals(this.getToken(), other.getToken()))
            && (Arrays.equals(this.getAuthentication(), other.getAuthentication()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_access_token
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getToken_id() == null) ? 0 : getToken_id().hashCode());
        result = prime * result + ((getAuthentication_id() == null) ? 0 : getAuthentication_id().hashCode());
        result = prime * result + ((getUser_name() == null) ? 0 : getUser_name().hashCode());
        result = prime * result + ((getClient_id() == null) ? 0 : getClient_id().hashCode());
        result = prime * result + ((getRefresh_token() == null) ? 0 : getRefresh_token().hashCode());
        result = prime * result + (Arrays.hashCode(getToken()));
        result = prime * result + (Arrays.hashCode(getAuthentication()));
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_access_token
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", token=").append(token);
        sb.append(", authentication=").append(authentication);
        sb.append("]");
        return sb.toString();
    }
}