package net.bndy.sc.service.sso.model;

import java.util.ArrayList;
import java.util.List;

public class OauthClientDetailsCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oauth_client_details
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oauth_client_details
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oauth_client_details
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    public OauthClientDetailsCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table oauth_client_details
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andClient_idIsNull() {
            addCriterion("client_id is null");
            return (Criteria) this;
        }

        public Criteria andClient_idIsNotNull() {
            addCriterion("client_id is not null");
            return (Criteria) this;
        }

        public Criteria andClient_idEqualTo(String value) {
            addCriterion("client_id =", value, "client_id");
            return (Criteria) this;
        }

        public Criteria andClient_idNotEqualTo(String value) {
            addCriterion("client_id <>", value, "client_id");
            return (Criteria) this;
        }

        public Criteria andClient_idGreaterThan(String value) {
            addCriterion("client_id >", value, "client_id");
            return (Criteria) this;
        }

        public Criteria andClient_idGreaterThanOrEqualTo(String value) {
            addCriterion("client_id >=", value, "client_id");
            return (Criteria) this;
        }

        public Criteria andClient_idLessThan(String value) {
            addCriterion("client_id <", value, "client_id");
            return (Criteria) this;
        }

        public Criteria andClient_idLessThanOrEqualTo(String value) {
            addCriterion("client_id <=", value, "client_id");
            return (Criteria) this;
        }

        public Criteria andClient_idLike(String value) {
            addCriterion("client_id like", value, "client_id");
            return (Criteria) this;
        }

        public Criteria andClient_idNotLike(String value) {
            addCriterion("client_id not like", value, "client_id");
            return (Criteria) this;
        }

        public Criteria andClient_idIn(List<String> values) {
            addCriterion("client_id in", values, "client_id");
            return (Criteria) this;
        }

        public Criteria andClient_idNotIn(List<String> values) {
            addCriterion("client_id not in", values, "client_id");
            return (Criteria) this;
        }

        public Criteria andClient_idBetween(String value1, String value2) {
            addCriterion("client_id between", value1, value2, "client_id");
            return (Criteria) this;
        }

        public Criteria andClient_idNotBetween(String value1, String value2) {
            addCriterion("client_id not between", value1, value2, "client_id");
            return (Criteria) this;
        }

        public Criteria andClient_nameIsNull() {
            addCriterion("client_name is null");
            return (Criteria) this;
        }

        public Criteria andClient_nameIsNotNull() {
            addCriterion("client_name is not null");
            return (Criteria) this;
        }

        public Criteria andClient_nameEqualTo(String value) {
            addCriterion("client_name =", value, "client_name");
            return (Criteria) this;
        }

        public Criteria andClient_nameNotEqualTo(String value) {
            addCriterion("client_name <>", value, "client_name");
            return (Criteria) this;
        }

        public Criteria andClient_nameGreaterThan(String value) {
            addCriterion("client_name >", value, "client_name");
            return (Criteria) this;
        }

        public Criteria andClient_nameGreaterThanOrEqualTo(String value) {
            addCriterion("client_name >=", value, "client_name");
            return (Criteria) this;
        }

        public Criteria andClient_nameLessThan(String value) {
            addCriterion("client_name <", value, "client_name");
            return (Criteria) this;
        }

        public Criteria andClient_nameLessThanOrEqualTo(String value) {
            addCriterion("client_name <=", value, "client_name");
            return (Criteria) this;
        }

        public Criteria andClient_nameLike(String value) {
            addCriterion("client_name like", value, "client_name");
            return (Criteria) this;
        }

        public Criteria andClient_nameNotLike(String value) {
            addCriterion("client_name not like", value, "client_name");
            return (Criteria) this;
        }

        public Criteria andClient_nameIn(List<String> values) {
            addCriterion("client_name in", values, "client_name");
            return (Criteria) this;
        }

        public Criteria andClient_nameNotIn(List<String> values) {
            addCriterion("client_name not in", values, "client_name");
            return (Criteria) this;
        }

        public Criteria andClient_nameBetween(String value1, String value2) {
            addCriterion("client_name between", value1, value2, "client_name");
            return (Criteria) this;
        }

        public Criteria andClient_nameNotBetween(String value1, String value2) {
            addCriterion("client_name not between", value1, value2, "client_name");
            return (Criteria) this;
        }

        public Criteria andClient_secretIsNull() {
            addCriterion("client_secret is null");
            return (Criteria) this;
        }

        public Criteria andClient_secretIsNotNull() {
            addCriterion("client_secret is not null");
            return (Criteria) this;
        }

        public Criteria andClient_secretEqualTo(String value) {
            addCriterion("client_secret =", value, "client_secret");
            return (Criteria) this;
        }

        public Criteria andClient_secretNotEqualTo(String value) {
            addCriterion("client_secret <>", value, "client_secret");
            return (Criteria) this;
        }

        public Criteria andClient_secretGreaterThan(String value) {
            addCriterion("client_secret >", value, "client_secret");
            return (Criteria) this;
        }

        public Criteria andClient_secretGreaterThanOrEqualTo(String value) {
            addCriterion("client_secret >=", value, "client_secret");
            return (Criteria) this;
        }

        public Criteria andClient_secretLessThan(String value) {
            addCriterion("client_secret <", value, "client_secret");
            return (Criteria) this;
        }

        public Criteria andClient_secretLessThanOrEqualTo(String value) {
            addCriterion("client_secret <=", value, "client_secret");
            return (Criteria) this;
        }

        public Criteria andClient_secretLike(String value) {
            addCriterion("client_secret like", value, "client_secret");
            return (Criteria) this;
        }

        public Criteria andClient_secretNotLike(String value) {
            addCriterion("client_secret not like", value, "client_secret");
            return (Criteria) this;
        }

        public Criteria andClient_secretIn(List<String> values) {
            addCriterion("client_secret in", values, "client_secret");
            return (Criteria) this;
        }

        public Criteria andClient_secretNotIn(List<String> values) {
            addCriterion("client_secret not in", values, "client_secret");
            return (Criteria) this;
        }

        public Criteria andClient_secretBetween(String value1, String value2) {
            addCriterion("client_secret between", value1, value2, "client_secret");
            return (Criteria) this;
        }

        public Criteria andClient_secretNotBetween(String value1, String value2) {
            addCriterion("client_secret not between", value1, value2, "client_secret");
            return (Criteria) this;
        }

        public Criteria andResource_idsIsNull() {
            addCriterion("resource_ids is null");
            return (Criteria) this;
        }

        public Criteria andResource_idsIsNotNull() {
            addCriterion("resource_ids is not null");
            return (Criteria) this;
        }

        public Criteria andResource_idsEqualTo(String value) {
            addCriterion("resource_ids =", value, "resource_ids");
            return (Criteria) this;
        }

        public Criteria andResource_idsNotEqualTo(String value) {
            addCriterion("resource_ids <>", value, "resource_ids");
            return (Criteria) this;
        }

        public Criteria andResource_idsGreaterThan(String value) {
            addCriterion("resource_ids >", value, "resource_ids");
            return (Criteria) this;
        }

        public Criteria andResource_idsGreaterThanOrEqualTo(String value) {
            addCriterion("resource_ids >=", value, "resource_ids");
            return (Criteria) this;
        }

        public Criteria andResource_idsLessThan(String value) {
            addCriterion("resource_ids <", value, "resource_ids");
            return (Criteria) this;
        }

        public Criteria andResource_idsLessThanOrEqualTo(String value) {
            addCriterion("resource_ids <=", value, "resource_ids");
            return (Criteria) this;
        }

        public Criteria andResource_idsLike(String value) {
            addCriterion("resource_ids like", value, "resource_ids");
            return (Criteria) this;
        }

        public Criteria andResource_idsNotLike(String value) {
            addCriterion("resource_ids not like", value, "resource_ids");
            return (Criteria) this;
        }

        public Criteria andResource_idsIn(List<String> values) {
            addCriterion("resource_ids in", values, "resource_ids");
            return (Criteria) this;
        }

        public Criteria andResource_idsNotIn(List<String> values) {
            addCriterion("resource_ids not in", values, "resource_ids");
            return (Criteria) this;
        }

        public Criteria andResource_idsBetween(String value1, String value2) {
            addCriterion("resource_ids between", value1, value2, "resource_ids");
            return (Criteria) this;
        }

        public Criteria andResource_idsNotBetween(String value1, String value2) {
            addCriterion("resource_ids not between", value1, value2, "resource_ids");
            return (Criteria) this;
        }

        public Criteria andScopeIsNull() {
            addCriterion("scope is null");
            return (Criteria) this;
        }

        public Criteria andScopeIsNotNull() {
            addCriterion("scope is not null");
            return (Criteria) this;
        }

        public Criteria andScopeEqualTo(String value) {
            addCriterion("scope =", value, "scope");
            return (Criteria) this;
        }

        public Criteria andScopeNotEqualTo(String value) {
            addCriterion("scope <>", value, "scope");
            return (Criteria) this;
        }

        public Criteria andScopeGreaterThan(String value) {
            addCriterion("scope >", value, "scope");
            return (Criteria) this;
        }

        public Criteria andScopeGreaterThanOrEqualTo(String value) {
            addCriterion("scope >=", value, "scope");
            return (Criteria) this;
        }

        public Criteria andScopeLessThan(String value) {
            addCriterion("scope <", value, "scope");
            return (Criteria) this;
        }

        public Criteria andScopeLessThanOrEqualTo(String value) {
            addCriterion("scope <=", value, "scope");
            return (Criteria) this;
        }

        public Criteria andScopeLike(String value) {
            addCriterion("scope like", value, "scope");
            return (Criteria) this;
        }

        public Criteria andScopeNotLike(String value) {
            addCriterion("scope not like", value, "scope");
            return (Criteria) this;
        }

        public Criteria andScopeIn(List<String> values) {
            addCriterion("scope in", values, "scope");
            return (Criteria) this;
        }

        public Criteria andScopeNotIn(List<String> values) {
            addCriterion("scope not in", values, "scope");
            return (Criteria) this;
        }

        public Criteria andScopeBetween(String value1, String value2) {
            addCriterion("scope between", value1, value2, "scope");
            return (Criteria) this;
        }

        public Criteria andScopeNotBetween(String value1, String value2) {
            addCriterion("scope not between", value1, value2, "scope");
            return (Criteria) this;
        }

        public Criteria andAuthorized_grant_typesIsNull() {
            addCriterion("authorized_grant_types is null");
            return (Criteria) this;
        }

        public Criteria andAuthorized_grant_typesIsNotNull() {
            addCriterion("authorized_grant_types is not null");
            return (Criteria) this;
        }

        public Criteria andAuthorized_grant_typesEqualTo(String value) {
            addCriterion("authorized_grant_types =", value, "authorized_grant_types");
            return (Criteria) this;
        }

        public Criteria andAuthorized_grant_typesNotEqualTo(String value) {
            addCriterion("authorized_grant_types <>", value, "authorized_grant_types");
            return (Criteria) this;
        }

        public Criteria andAuthorized_grant_typesGreaterThan(String value) {
            addCriterion("authorized_grant_types >", value, "authorized_grant_types");
            return (Criteria) this;
        }

        public Criteria andAuthorized_grant_typesGreaterThanOrEqualTo(String value) {
            addCriterion("authorized_grant_types >=", value, "authorized_grant_types");
            return (Criteria) this;
        }

        public Criteria andAuthorized_grant_typesLessThan(String value) {
            addCriterion("authorized_grant_types <", value, "authorized_grant_types");
            return (Criteria) this;
        }

        public Criteria andAuthorized_grant_typesLessThanOrEqualTo(String value) {
            addCriterion("authorized_grant_types <=", value, "authorized_grant_types");
            return (Criteria) this;
        }

        public Criteria andAuthorized_grant_typesLike(String value) {
            addCriterion("authorized_grant_types like", value, "authorized_grant_types");
            return (Criteria) this;
        }

        public Criteria andAuthorized_grant_typesNotLike(String value) {
            addCriterion("authorized_grant_types not like", value, "authorized_grant_types");
            return (Criteria) this;
        }

        public Criteria andAuthorized_grant_typesIn(List<String> values) {
            addCriterion("authorized_grant_types in", values, "authorized_grant_types");
            return (Criteria) this;
        }

        public Criteria andAuthorized_grant_typesNotIn(List<String> values) {
            addCriterion("authorized_grant_types not in", values, "authorized_grant_types");
            return (Criteria) this;
        }

        public Criteria andAuthorized_grant_typesBetween(String value1, String value2) {
            addCriterion("authorized_grant_types between", value1, value2, "authorized_grant_types");
            return (Criteria) this;
        }

        public Criteria andAuthorized_grant_typesNotBetween(String value1, String value2) {
            addCriterion("authorized_grant_types not between", value1, value2, "authorized_grant_types");
            return (Criteria) this;
        }

        public Criteria andWeb_server_redirect_uriIsNull() {
            addCriterion("web_server_redirect_uri is null");
            return (Criteria) this;
        }

        public Criteria andWeb_server_redirect_uriIsNotNull() {
            addCriterion("web_server_redirect_uri is not null");
            return (Criteria) this;
        }

        public Criteria andWeb_server_redirect_uriEqualTo(String value) {
            addCriterion("web_server_redirect_uri =", value, "web_server_redirect_uri");
            return (Criteria) this;
        }

        public Criteria andWeb_server_redirect_uriNotEqualTo(String value) {
            addCriterion("web_server_redirect_uri <>", value, "web_server_redirect_uri");
            return (Criteria) this;
        }

        public Criteria andWeb_server_redirect_uriGreaterThan(String value) {
            addCriterion("web_server_redirect_uri >", value, "web_server_redirect_uri");
            return (Criteria) this;
        }

        public Criteria andWeb_server_redirect_uriGreaterThanOrEqualTo(String value) {
            addCriterion("web_server_redirect_uri >=", value, "web_server_redirect_uri");
            return (Criteria) this;
        }

        public Criteria andWeb_server_redirect_uriLessThan(String value) {
            addCriterion("web_server_redirect_uri <", value, "web_server_redirect_uri");
            return (Criteria) this;
        }

        public Criteria andWeb_server_redirect_uriLessThanOrEqualTo(String value) {
            addCriterion("web_server_redirect_uri <=", value, "web_server_redirect_uri");
            return (Criteria) this;
        }

        public Criteria andWeb_server_redirect_uriLike(String value) {
            addCriterion("web_server_redirect_uri like", value, "web_server_redirect_uri");
            return (Criteria) this;
        }

        public Criteria andWeb_server_redirect_uriNotLike(String value) {
            addCriterion("web_server_redirect_uri not like", value, "web_server_redirect_uri");
            return (Criteria) this;
        }

        public Criteria andWeb_server_redirect_uriIn(List<String> values) {
            addCriterion("web_server_redirect_uri in", values, "web_server_redirect_uri");
            return (Criteria) this;
        }

        public Criteria andWeb_server_redirect_uriNotIn(List<String> values) {
            addCriterion("web_server_redirect_uri not in", values, "web_server_redirect_uri");
            return (Criteria) this;
        }

        public Criteria andWeb_server_redirect_uriBetween(String value1, String value2) {
            addCriterion("web_server_redirect_uri between", value1, value2, "web_server_redirect_uri");
            return (Criteria) this;
        }

        public Criteria andWeb_server_redirect_uriNotBetween(String value1, String value2) {
            addCriterion("web_server_redirect_uri not between", value1, value2, "web_server_redirect_uri");
            return (Criteria) this;
        }

        public Criteria andAuthoritiesIsNull() {
            addCriterion("authorities is null");
            return (Criteria) this;
        }

        public Criteria andAuthoritiesIsNotNull() {
            addCriterion("authorities is not null");
            return (Criteria) this;
        }

        public Criteria andAuthoritiesEqualTo(String value) {
            addCriterion("authorities =", value, "authorities");
            return (Criteria) this;
        }

        public Criteria andAuthoritiesNotEqualTo(String value) {
            addCriterion("authorities <>", value, "authorities");
            return (Criteria) this;
        }

        public Criteria andAuthoritiesGreaterThan(String value) {
            addCriterion("authorities >", value, "authorities");
            return (Criteria) this;
        }

        public Criteria andAuthoritiesGreaterThanOrEqualTo(String value) {
            addCriterion("authorities >=", value, "authorities");
            return (Criteria) this;
        }

        public Criteria andAuthoritiesLessThan(String value) {
            addCriterion("authorities <", value, "authorities");
            return (Criteria) this;
        }

        public Criteria andAuthoritiesLessThanOrEqualTo(String value) {
            addCriterion("authorities <=", value, "authorities");
            return (Criteria) this;
        }

        public Criteria andAuthoritiesLike(String value) {
            addCriterion("authorities like", value, "authorities");
            return (Criteria) this;
        }

        public Criteria andAuthoritiesNotLike(String value) {
            addCriterion("authorities not like", value, "authorities");
            return (Criteria) this;
        }

        public Criteria andAuthoritiesIn(List<String> values) {
            addCriterion("authorities in", values, "authorities");
            return (Criteria) this;
        }

        public Criteria andAuthoritiesNotIn(List<String> values) {
            addCriterion("authorities not in", values, "authorities");
            return (Criteria) this;
        }

        public Criteria andAuthoritiesBetween(String value1, String value2) {
            addCriterion("authorities between", value1, value2, "authorities");
            return (Criteria) this;
        }

        public Criteria andAuthoritiesNotBetween(String value1, String value2) {
            addCriterion("authorities not between", value1, value2, "authorities");
            return (Criteria) this;
        }

        public Criteria andAccess_token_validityIsNull() {
            addCriterion("access_token_validity is null");
            return (Criteria) this;
        }

        public Criteria andAccess_token_validityIsNotNull() {
            addCriterion("access_token_validity is not null");
            return (Criteria) this;
        }

        public Criteria andAccess_token_validityEqualTo(Integer value) {
            addCriterion("access_token_validity =", value, "access_token_validity");
            return (Criteria) this;
        }

        public Criteria andAccess_token_validityNotEqualTo(Integer value) {
            addCriterion("access_token_validity <>", value, "access_token_validity");
            return (Criteria) this;
        }

        public Criteria andAccess_token_validityGreaterThan(Integer value) {
            addCriterion("access_token_validity >", value, "access_token_validity");
            return (Criteria) this;
        }

        public Criteria andAccess_token_validityGreaterThanOrEqualTo(Integer value) {
            addCriterion("access_token_validity >=", value, "access_token_validity");
            return (Criteria) this;
        }

        public Criteria andAccess_token_validityLessThan(Integer value) {
            addCriterion("access_token_validity <", value, "access_token_validity");
            return (Criteria) this;
        }

        public Criteria andAccess_token_validityLessThanOrEqualTo(Integer value) {
            addCriterion("access_token_validity <=", value, "access_token_validity");
            return (Criteria) this;
        }

        public Criteria andAccess_token_validityIn(List<Integer> values) {
            addCriterion("access_token_validity in", values, "access_token_validity");
            return (Criteria) this;
        }

        public Criteria andAccess_token_validityNotIn(List<Integer> values) {
            addCriterion("access_token_validity not in", values, "access_token_validity");
            return (Criteria) this;
        }

        public Criteria andAccess_token_validityBetween(Integer value1, Integer value2) {
            addCriterion("access_token_validity between", value1, value2, "access_token_validity");
            return (Criteria) this;
        }

        public Criteria andAccess_token_validityNotBetween(Integer value1, Integer value2) {
            addCriterion("access_token_validity not between", value1, value2, "access_token_validity");
            return (Criteria) this;
        }

        public Criteria andRefresh_token_validityIsNull() {
            addCriterion("refresh_token_validity is null");
            return (Criteria) this;
        }

        public Criteria andRefresh_token_validityIsNotNull() {
            addCriterion("refresh_token_validity is not null");
            return (Criteria) this;
        }

        public Criteria andRefresh_token_validityEqualTo(Integer value) {
            addCriterion("refresh_token_validity =", value, "refresh_token_validity");
            return (Criteria) this;
        }

        public Criteria andRefresh_token_validityNotEqualTo(Integer value) {
            addCriterion("refresh_token_validity <>", value, "refresh_token_validity");
            return (Criteria) this;
        }

        public Criteria andRefresh_token_validityGreaterThan(Integer value) {
            addCriterion("refresh_token_validity >", value, "refresh_token_validity");
            return (Criteria) this;
        }

        public Criteria andRefresh_token_validityGreaterThanOrEqualTo(Integer value) {
            addCriterion("refresh_token_validity >=", value, "refresh_token_validity");
            return (Criteria) this;
        }

        public Criteria andRefresh_token_validityLessThan(Integer value) {
            addCriterion("refresh_token_validity <", value, "refresh_token_validity");
            return (Criteria) this;
        }

        public Criteria andRefresh_token_validityLessThanOrEqualTo(Integer value) {
            addCriterion("refresh_token_validity <=", value, "refresh_token_validity");
            return (Criteria) this;
        }

        public Criteria andRefresh_token_validityIn(List<Integer> values) {
            addCriterion("refresh_token_validity in", values, "refresh_token_validity");
            return (Criteria) this;
        }

        public Criteria andRefresh_token_validityNotIn(List<Integer> values) {
            addCriterion("refresh_token_validity not in", values, "refresh_token_validity");
            return (Criteria) this;
        }

        public Criteria andRefresh_token_validityBetween(Integer value1, Integer value2) {
            addCriterion("refresh_token_validity between", value1, value2, "refresh_token_validity");
            return (Criteria) this;
        }

        public Criteria andRefresh_token_validityNotBetween(Integer value1, Integer value2) {
            addCriterion("refresh_token_validity not between", value1, value2, "refresh_token_validity");
            return (Criteria) this;
        }

        public Criteria andAdditional_informationIsNull() {
            addCriterion("additional_information is null");
            return (Criteria) this;
        }

        public Criteria andAdditional_informationIsNotNull() {
            addCriterion("additional_information is not null");
            return (Criteria) this;
        }

        public Criteria andAdditional_informationEqualTo(String value) {
            addCriterion("additional_information =", value, "additional_information");
            return (Criteria) this;
        }

        public Criteria andAdditional_informationNotEqualTo(String value) {
            addCriterion("additional_information <>", value, "additional_information");
            return (Criteria) this;
        }

        public Criteria andAdditional_informationGreaterThan(String value) {
            addCriterion("additional_information >", value, "additional_information");
            return (Criteria) this;
        }

        public Criteria andAdditional_informationGreaterThanOrEqualTo(String value) {
            addCriterion("additional_information >=", value, "additional_information");
            return (Criteria) this;
        }

        public Criteria andAdditional_informationLessThan(String value) {
            addCriterion("additional_information <", value, "additional_information");
            return (Criteria) this;
        }

        public Criteria andAdditional_informationLessThanOrEqualTo(String value) {
            addCriterion("additional_information <=", value, "additional_information");
            return (Criteria) this;
        }

        public Criteria andAdditional_informationLike(String value) {
            addCriterion("additional_information like", value, "additional_information");
            return (Criteria) this;
        }

        public Criteria andAdditional_informationNotLike(String value) {
            addCriterion("additional_information not like", value, "additional_information");
            return (Criteria) this;
        }

        public Criteria andAdditional_informationIn(List<String> values) {
            addCriterion("additional_information in", values, "additional_information");
            return (Criteria) this;
        }

        public Criteria andAdditional_informationNotIn(List<String> values) {
            addCriterion("additional_information not in", values, "additional_information");
            return (Criteria) this;
        }

        public Criteria andAdditional_informationBetween(String value1, String value2) {
            addCriterion("additional_information between", value1, value2, "additional_information");
            return (Criteria) this;
        }

        public Criteria andAdditional_informationNotBetween(String value1, String value2) {
            addCriterion("additional_information not between", value1, value2, "additional_information");
            return (Criteria) this;
        }

        public Criteria andAutoapproveIsNull() {
            addCriterion("autoapprove is null");
            return (Criteria) this;
        }

        public Criteria andAutoapproveIsNotNull() {
            addCriterion("autoapprove is not null");
            return (Criteria) this;
        }

        public Criteria andAutoapproveEqualTo(Byte value) {
            addCriterion("autoapprove =", value, "autoapprove");
            return (Criteria) this;
        }

        public Criteria andAutoapproveNotEqualTo(Byte value) {
            addCriterion("autoapprove <>", value, "autoapprove");
            return (Criteria) this;
        }

        public Criteria andAutoapproveGreaterThan(Byte value) {
            addCriterion("autoapprove >", value, "autoapprove");
            return (Criteria) this;
        }

        public Criteria andAutoapproveGreaterThanOrEqualTo(Byte value) {
            addCriterion("autoapprove >=", value, "autoapprove");
            return (Criteria) this;
        }

        public Criteria andAutoapproveLessThan(Byte value) {
            addCriterion("autoapprove <", value, "autoapprove");
            return (Criteria) this;
        }

        public Criteria andAutoapproveLessThanOrEqualTo(Byte value) {
            addCriterion("autoapprove <=", value, "autoapprove");
            return (Criteria) this;
        }

        public Criteria andAutoapproveIn(List<Byte> values) {
            addCriterion("autoapprove in", values, "autoapprove");
            return (Criteria) this;
        }

        public Criteria andAutoapproveNotIn(List<Byte> values) {
            addCriterion("autoapprove not in", values, "autoapprove");
            return (Criteria) this;
        }

        public Criteria andAutoapproveBetween(Byte value1, Byte value2) {
            addCriterion("autoapprove between", value1, value2, "autoapprove");
            return (Criteria) this;
        }

        public Criteria andAutoapproveNotBetween(Byte value1, Byte value2) {
            addCriterion("autoapprove not between", value1, value2, "autoapprove");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table oauth_client_details
     *
     * @mbg.generated do_not_delete_during_merge Tue Aug 07 18:09:57 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table oauth_client_details
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}