package net.bndy.sc.service.sso.model;

import java.util.ArrayList;
import java.util.List;

public class OauthAccessTokenCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oauth_access_token
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oauth_access_token
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oauth_access_token
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_access_token
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    public OauthAccessTokenCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_access_token
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_access_token
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_access_token
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_access_token
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_access_token
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_access_token
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_access_token
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_access_token
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_access_token
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_access_token
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table oauth_access_token
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andToken_idIsNull() {
            addCriterion("token_id is null");
            return (Criteria) this;
        }

        public Criteria andToken_idIsNotNull() {
            addCriterion("token_id is not null");
            return (Criteria) this;
        }

        public Criteria andToken_idEqualTo(String value) {
            addCriterion("token_id =", value, "token_id");
            return (Criteria) this;
        }

        public Criteria andToken_idNotEqualTo(String value) {
            addCriterion("token_id <>", value, "token_id");
            return (Criteria) this;
        }

        public Criteria andToken_idGreaterThan(String value) {
            addCriterion("token_id >", value, "token_id");
            return (Criteria) this;
        }

        public Criteria andToken_idGreaterThanOrEqualTo(String value) {
            addCriterion("token_id >=", value, "token_id");
            return (Criteria) this;
        }

        public Criteria andToken_idLessThan(String value) {
            addCriterion("token_id <", value, "token_id");
            return (Criteria) this;
        }

        public Criteria andToken_idLessThanOrEqualTo(String value) {
            addCriterion("token_id <=", value, "token_id");
            return (Criteria) this;
        }

        public Criteria andToken_idLike(String value) {
            addCriterion("token_id like", value, "token_id");
            return (Criteria) this;
        }

        public Criteria andToken_idNotLike(String value) {
            addCriterion("token_id not like", value, "token_id");
            return (Criteria) this;
        }

        public Criteria andToken_idIn(List<String> values) {
            addCriterion("token_id in", values, "token_id");
            return (Criteria) this;
        }

        public Criteria andToken_idNotIn(List<String> values) {
            addCriterion("token_id not in", values, "token_id");
            return (Criteria) this;
        }

        public Criteria andToken_idBetween(String value1, String value2) {
            addCriterion("token_id between", value1, value2, "token_id");
            return (Criteria) this;
        }

        public Criteria andToken_idNotBetween(String value1, String value2) {
            addCriterion("token_id not between", value1, value2, "token_id");
            return (Criteria) this;
        }

        public Criteria andAuthentication_idIsNull() {
            addCriterion("authentication_id is null");
            return (Criteria) this;
        }

        public Criteria andAuthentication_idIsNotNull() {
            addCriterion("authentication_id is not null");
            return (Criteria) this;
        }

        public Criteria andAuthentication_idEqualTo(String value) {
            addCriterion("authentication_id =", value, "authentication_id");
            return (Criteria) this;
        }

        public Criteria andAuthentication_idNotEqualTo(String value) {
            addCriterion("authentication_id <>", value, "authentication_id");
            return (Criteria) this;
        }

        public Criteria andAuthentication_idGreaterThan(String value) {
            addCriterion("authentication_id >", value, "authentication_id");
            return (Criteria) this;
        }

        public Criteria andAuthentication_idGreaterThanOrEqualTo(String value) {
            addCriterion("authentication_id >=", value, "authentication_id");
            return (Criteria) this;
        }

        public Criteria andAuthentication_idLessThan(String value) {
            addCriterion("authentication_id <", value, "authentication_id");
            return (Criteria) this;
        }

        public Criteria andAuthentication_idLessThanOrEqualTo(String value) {
            addCriterion("authentication_id <=", value, "authentication_id");
            return (Criteria) this;
        }

        public Criteria andAuthentication_idLike(String value) {
            addCriterion("authentication_id like", value, "authentication_id");
            return (Criteria) this;
        }

        public Criteria andAuthentication_idNotLike(String value) {
            addCriterion("authentication_id not like", value, "authentication_id");
            return (Criteria) this;
        }

        public Criteria andAuthentication_idIn(List<String> values) {
            addCriterion("authentication_id in", values, "authentication_id");
            return (Criteria) this;
        }

        public Criteria andAuthentication_idNotIn(List<String> values) {
            addCriterion("authentication_id not in", values, "authentication_id");
            return (Criteria) this;
        }

        public Criteria andAuthentication_idBetween(String value1, String value2) {
            addCriterion("authentication_id between", value1, value2, "authentication_id");
            return (Criteria) this;
        }

        public Criteria andAuthentication_idNotBetween(String value1, String value2) {
            addCriterion("authentication_id not between", value1, value2, "authentication_id");
            return (Criteria) this;
        }

        public Criteria andUser_nameIsNull() {
            addCriterion("user_name is null");
            return (Criteria) this;
        }

        public Criteria andUser_nameIsNotNull() {
            addCriterion("user_name is not null");
            return (Criteria) this;
        }

        public Criteria andUser_nameEqualTo(String value) {
            addCriterion("user_name =", value, "user_name");
            return (Criteria) this;
        }

        public Criteria andUser_nameNotEqualTo(String value) {
            addCriterion("user_name <>", value, "user_name");
            return (Criteria) this;
        }

        public Criteria andUser_nameGreaterThan(String value) {
            addCriterion("user_name >", value, "user_name");
            return (Criteria) this;
        }

        public Criteria andUser_nameGreaterThanOrEqualTo(String value) {
            addCriterion("user_name >=", value, "user_name");
            return (Criteria) this;
        }

        public Criteria andUser_nameLessThan(String value) {
            addCriterion("user_name <", value, "user_name");
            return (Criteria) this;
        }

        public Criteria andUser_nameLessThanOrEqualTo(String value) {
            addCriterion("user_name <=", value, "user_name");
            return (Criteria) this;
        }

        public Criteria andUser_nameLike(String value) {
            addCriterion("user_name like", value, "user_name");
            return (Criteria) this;
        }

        public Criteria andUser_nameNotLike(String value) {
            addCriterion("user_name not like", value, "user_name");
            return (Criteria) this;
        }

        public Criteria andUser_nameIn(List<String> values) {
            addCriterion("user_name in", values, "user_name");
            return (Criteria) this;
        }

        public Criteria andUser_nameNotIn(List<String> values) {
            addCriterion("user_name not in", values, "user_name");
            return (Criteria) this;
        }

        public Criteria andUser_nameBetween(String value1, String value2) {
            addCriterion("user_name between", value1, value2, "user_name");
            return (Criteria) this;
        }

        public Criteria andUser_nameNotBetween(String value1, String value2) {
            addCriterion("user_name not between", value1, value2, "user_name");
            return (Criteria) this;
        }

        public Criteria andClient_idIsNull() {
            addCriterion("client_id is null");
            return (Criteria) this;
        }

        public Criteria andClient_idIsNotNull() {
            addCriterion("client_id is not null");
            return (Criteria) this;
        }

        public Criteria andClient_idEqualTo(String value) {
            addCriterion("client_id =", value, "client_id");
            return (Criteria) this;
        }

        public Criteria andClient_idNotEqualTo(String value) {
            addCriterion("client_id <>", value, "client_id");
            return (Criteria) this;
        }

        public Criteria andClient_idGreaterThan(String value) {
            addCriterion("client_id >", value, "client_id");
            return (Criteria) this;
        }

        public Criteria andClient_idGreaterThanOrEqualTo(String value) {
            addCriterion("client_id >=", value, "client_id");
            return (Criteria) this;
        }

        public Criteria andClient_idLessThan(String value) {
            addCriterion("client_id <", value, "client_id");
            return (Criteria) this;
        }

        public Criteria andClient_idLessThanOrEqualTo(String value) {
            addCriterion("client_id <=", value, "client_id");
            return (Criteria) this;
        }

        public Criteria andClient_idLike(String value) {
            addCriterion("client_id like", value, "client_id");
            return (Criteria) this;
        }

        public Criteria andClient_idNotLike(String value) {
            addCriterion("client_id not like", value, "client_id");
            return (Criteria) this;
        }

        public Criteria andClient_idIn(List<String> values) {
            addCriterion("client_id in", values, "client_id");
            return (Criteria) this;
        }

        public Criteria andClient_idNotIn(List<String> values) {
            addCriterion("client_id not in", values, "client_id");
            return (Criteria) this;
        }

        public Criteria andClient_idBetween(String value1, String value2) {
            addCriterion("client_id between", value1, value2, "client_id");
            return (Criteria) this;
        }

        public Criteria andClient_idNotBetween(String value1, String value2) {
            addCriterion("client_id not between", value1, value2, "client_id");
            return (Criteria) this;
        }

        public Criteria andRefresh_tokenIsNull() {
            addCriterion("refresh_token is null");
            return (Criteria) this;
        }

        public Criteria andRefresh_tokenIsNotNull() {
            addCriterion("refresh_token is not null");
            return (Criteria) this;
        }

        public Criteria andRefresh_tokenEqualTo(String value) {
            addCriterion("refresh_token =", value, "refresh_token");
            return (Criteria) this;
        }

        public Criteria andRefresh_tokenNotEqualTo(String value) {
            addCriterion("refresh_token <>", value, "refresh_token");
            return (Criteria) this;
        }

        public Criteria andRefresh_tokenGreaterThan(String value) {
            addCriterion("refresh_token >", value, "refresh_token");
            return (Criteria) this;
        }

        public Criteria andRefresh_tokenGreaterThanOrEqualTo(String value) {
            addCriterion("refresh_token >=", value, "refresh_token");
            return (Criteria) this;
        }

        public Criteria andRefresh_tokenLessThan(String value) {
            addCriterion("refresh_token <", value, "refresh_token");
            return (Criteria) this;
        }

        public Criteria andRefresh_tokenLessThanOrEqualTo(String value) {
            addCriterion("refresh_token <=", value, "refresh_token");
            return (Criteria) this;
        }

        public Criteria andRefresh_tokenLike(String value) {
            addCriterion("refresh_token like", value, "refresh_token");
            return (Criteria) this;
        }

        public Criteria andRefresh_tokenNotLike(String value) {
            addCriterion("refresh_token not like", value, "refresh_token");
            return (Criteria) this;
        }

        public Criteria andRefresh_tokenIn(List<String> values) {
            addCriterion("refresh_token in", values, "refresh_token");
            return (Criteria) this;
        }

        public Criteria andRefresh_tokenNotIn(List<String> values) {
            addCriterion("refresh_token not in", values, "refresh_token");
            return (Criteria) this;
        }

        public Criteria andRefresh_tokenBetween(String value1, String value2) {
            addCriterion("refresh_token between", value1, value2, "refresh_token");
            return (Criteria) this;
        }

        public Criteria andRefresh_tokenNotBetween(String value1, String value2) {
            addCriterion("refresh_token not between", value1, value2, "refresh_token");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table oauth_access_token
     *
     * @mbg.generated do_not_delete_during_merge Tue Aug 07 18:09:57 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table oauth_access_token
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}