package net.bndy.sc.service.sso.model;

import java.io.Serializable;
import java.util.Date;

public class OauthApprovals implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_approvals.userId
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_approvals.clientId
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    private String clientId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_approvals.scope
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    private String scope;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_approvals.status
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_approvals.expiresAt
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    private Date expiresAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_approvals.lastModifiedAt
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    private Date lastModifiedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oauth_approvals
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_approvals.userId
     *
     * @return the value of oauth_approvals.userId
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_approvals.userId
     *
     * @param userId the value for oauth_approvals.userId
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_approvals.clientId
     *
     * @return the value of oauth_approvals.clientId
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    public String getClientId() {
        return clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_approvals.clientId
     *
     * @param clientId the value for oauth_approvals.clientId
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    public void setClientId(String clientId) {
        this.clientId = clientId == null ? null : clientId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_approvals.scope
     *
     * @return the value of oauth_approvals.scope
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    public String getScope() {
        return scope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_approvals.scope
     *
     * @param scope the value for oauth_approvals.scope
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    public void setScope(String scope) {
        this.scope = scope == null ? null : scope.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_approvals.status
     *
     * @return the value of oauth_approvals.status
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_approvals.status
     *
     * @param status the value for oauth_approvals.status
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_approvals.expiresAt
     *
     * @return the value of oauth_approvals.expiresAt
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    public Date getExpiresAt() {
        return expiresAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_approvals.expiresAt
     *
     * @param expiresAt the value for oauth_approvals.expiresAt
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    public void setExpiresAt(Date expiresAt) {
        this.expiresAt = expiresAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_approvals.lastModifiedAt
     *
     * @return the value of oauth_approvals.lastModifiedAt
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    public Date getLastModifiedAt() {
        return lastModifiedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_approvals.lastModifiedAt
     *
     * @param lastModifiedAt the value for oauth_approvals.lastModifiedAt
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    public void setLastModifiedAt(Date lastModifiedAt) {
        this.lastModifiedAt = lastModifiedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_approvals
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        OauthApprovals other = (OauthApprovals) that;
        return (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getClientId() == null ? other.getClientId() == null : this.getClientId().equals(other.getClientId()))
            && (this.getScope() == null ? other.getScope() == null : this.getScope().equals(other.getScope()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getExpiresAt() == null ? other.getExpiresAt() == null : this.getExpiresAt().equals(other.getExpiresAt()))
            && (this.getLastModifiedAt() == null ? other.getLastModifiedAt() == null : this.getLastModifiedAt().equals(other.getLastModifiedAt()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_approvals
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getClientId() == null) ? 0 : getClientId().hashCode());
        result = prime * result + ((getScope() == null) ? 0 : getScope().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getExpiresAt() == null) ? 0 : getExpiresAt().hashCode());
        result = prime * result + ((getLastModifiedAt() == null) ? 0 : getLastModifiedAt().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_approvals
     *
     * @mbg.generated Tue Aug 07 18:09:57 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId=").append(userId);
        sb.append(", clientId=").append(clientId);
        sb.append(", scope=").append(scope);
        sb.append(", status=").append(status);
        sb.append(", expiresAt=").append(expiresAt);
        sb.append(", lastModifiedAt=").append(lastModifiedAt);
        sb.append("]");
        return sb.toString();
    }
}